ASIA_REMAIN = [
    [ 'ir', 0 ],
    [ 'ph', 0 ],
    [ 'th', 0 ],
    [ 'om', 0 ],
    [ 'ye', 0 ],
    [ 'bd', 0 ],
    [ 'sp', 0 ],
    [ 'bh', 0 ],
    [ 'mm', 0 ],
    [ 'id', 0 ],
    [ 'ru', 0 ],
    [ 'sh', 0 ],
    [ 'az', 0 ],
    [ 'am', 0 ],
    [ 'vn', 0 ],
    [ 'tj', 0 ],
    [ 'uz', 0 ],
    [ 'tl', 0 ],
    [ 'kh', 0 ],
    [ 'bt', 0 ],
    [ 'ge', 0 ],
    [ 'kz', 0 ],
    [ 'sy', 0 ],
    [ 'jo', 0 ],
    [ 'tm', 0 ],
    [ 'cnm', 0 ],
    [ 'mn', 0 ],
    [ 'kw', 0 ],
    [ 'iq', 0 ],
    [ 'ae', 0 ],
    [ 'la', 0 ],
    [ 'pk', 0 ],
    [ 'jk', 0 ],
    [ 'qa', 0 ],
    [ 'tr', 0 ],
    [ 'bn', 0 ],
    [ 'af', 0 ],
    [ 'kp', 0 ],
    [ 'lb', 0 ],
    [ 'nc', 0 ],
    [ 'cy', 0 ],
    [ 'np', 0 ],
    [ 'lk', 0 ],
    [ 'kg', 0 ]
]
NORTH_AMERICA_REMAIN = [
    ['gl', 0],
    ['lc', 0],
    ['um', 0],
    ['vi', 0],
    ['cu', 0],
    ['kn', 0],
    ['ni', 0],
    ['gd', 0],
    ['dm', 0],
    ['ag', 0],
    ['tt', 0],
    ['sw', 0],
    ['bb', 0],
    ['jm', 0],
    ['bu', 0],
    ['bs', 0],
    ['vc', 0],
    ['ht', 0],
    ['sv', 0],
    ['hn', 0],
    ['do', 0],
    ['bz', 0],
    ['gt', 0],
    ['cr', 0],
    ['pr', 0],
    ['pa', 0]
]
SOUTH_AMERICA_REMAIN = [
    ['ec', 0],
    ['ve', 0],
    ['pe', 0],
    ['uy', 0],
    ['py', 0],
    ['bo', 0],
    ['sr', 0],
    ['gy', 0],
    ['gb', 0],
    ['co', 0]
]
EUROPE_REMAIN = [
    ['fo', 0],
    ['hr', 0],
    ['ee', 0],
    ['bg', 0],
    ['sm', 0],
    ['va', 0],
    ['tr', 0],
    ['mt', 0],
    ['ua', 0],
    ['cy', 0],
    ['pt', 0],
    ['lt', 0],
    ['si', 0],
    ['ba', 0],
    ['mc', 0],
    ['al', 0],
    ['cnm', 0],
    ['nc', 0],
    ['rs', 0],
    ['ro', 0],
    ['me', 0],
    ['li', 0],
    ['sk', 0],
    ['hu', 0],
    ['ad', 0],
    ['lu', 0],
    ['kv', 0],
    ['pl', 0],
    ['mk', 0],
    ['lv', 0],
    ['by', 0],
    ['is', 0],
    ['md', 0],
    ['cz', 0]
]
AFRICA_REMAIN = [
    ['ug', 0],
    ['ng', 0],
    ['st', 0],
    ['tz', 0],
    ['sl', 0],
    ['gw', 0],
    ['cv', 0],
    ['sc', 0],
    ['tn', 0],
    ['mg', 0],
    ['ke', 0],
    ['cd', 0],
    ['fr', 0],
    ['mr', 0],
    ['dz', 0],
    ['er', 0],
    ['gq', 0],
    ['mu', 0],
    ['sn', 0],
    ['km', 0],
    ['et', 0],
    ['ci', 0],
    ['gh', 0],
    ['zm', 0],
    ['na', 0],
    ['rw', 0],
    ['sx', 0],
    ['so', 0],
    ['cm', 0],
    ['cg', 0],
    ['eh', 0],
    ['bj', 0],
    ['bf', 0],
    ['tg', 0],
    ['ne', 0],
    ['ly', 0],
    ['lr', 0],
    ['mw', 0],
    ['gm', 0],
    ['td', 0],
    ['ga', 0],
    ['dj', 0],
    ['bi', 0],
    ['ao', 0],
    ['gn', 0],
    ['zw', 0],
    ['mz', 0],
    ['sz', 0],
    ['ml', 0],
    ['bw', 0],
    ['sd', 0],
    ['ma', 0],
    ['eg', 0],
    ['ls', 0],
    ['ss', 0],
    ['cf', 0]
 ]
OCEANIA_REMAIN = [
    ['id', 0],
    ['pw', 0],
    ['sb', 0],
    ['nr', 0],
    ['tv', 0],
    ['pg', 0],
    ['mh', 0],
    ['fm', 0],
    ['vu', 0],
    ['my', 0],
    ['fj', 0],
    ['ph', 0]
]

def get_remain_code(map_scale):
    if map_scale == 'world-continents':
        return []
    elif map_scale == 'asia':
        return ASIA_REMAIN
    elif map_scale == 'north-america':
        return NORTH_AMERICA_REMAIN
    elif map_scale == 'south-america':
        return SOUTH_AMERICA_REMAIN
    elif map_scale == 'europe':
        return EUROPE_REMAIN
    elif map_scale == 'africa':
        return AFRICA_REMAIN
    elif map_scale == 'oceania':
        return OCEANIA_REMAIN
